include:
    - 'https://raw.githubusercontent.com/JuliaGPU/gitlab-ci/master/templates/v6.yml'

# CUDA

nvidia:test:v1.0:
    image: nvidia/opencl:devel-ubuntu16.04
    extends:
        - .test
        - .julia:1.0
    tags:
        - nvidia

nvidia:test:v1.1:
    image: nvidia/opencl:devel-ubuntu16.04
    extends:
        - .test
        - .julia:1.1
    tags:
        - nvidia

nvidia:test:v1.2:
    image: nvidia/opencl:devel-ubuntu16.04
    extends:
        - .test
        - .julia:1.2
    tags:
        - nvidia

nvidia:test:v1.3:
    image: nvidia/opencl:devel-ubuntu16.04
    extends:
        - .test
        - .julia:1.3
    tags:
        - nvidia

nvidia:test:v1.4:
    image: nvidia/opencl:devel-ubuntu16.04
    extends:
        - .test
        - .julia:1.4
    tags:
        - nvidia

nvidia:test:nightly:
    image: nvidia/opencl:devel-ubuntu16.04
    extends:
        - .test
        - .julia:nightly
    tags:
        - nvidia
    allow_failure: true

# ROCm

amd:test:v1.0:
    image: rocm/dev-ubuntu-18.04
    extends:
        - .test
        - .julia:1.0
    variables:
        CI_APT_INSTALL: 'rocm-opencl'
    tags:
        - rocm

amd:test:v1.1:
    image: rocm/dev-ubuntu-18.04
    extends:
        - .test
        - .julia:1.1
    variables:
        CI_APT_INSTALL: 'rocm-opencl'
    tags:
        - rocm

amd:test:v1.2:
    image: rocm/dev-ubuntu-18.04
    extends:
        - .test
        - .julia:1.2
    variables:
        CI_APT_INSTALL: 'rocm-opencl'
    tags:
        - rocm

amd:test:v1.3:
    image: rocm/dev-ubuntu-18.04
    extends:
        - .test
        - .julia:1.3
    variables:
        CI_APT_INSTALL: 'rocm-opencl'
    tags:
        - rocm

amd:test:v1.4:
    image: rocm/dev-ubuntu-18.04
    extends:
        - .test
        - .julia:1.4
    variables:
        CI_APT_INSTALL: 'rocm-opencl'
    tags:
        - rocm

amd:test:nightly:
    image: rocm/dev-ubuntu-18.04
    extends:
        - .test
        - .julia:nightly
    variables:
        CI_APT_INSTALL: 'rocm-opencl'
    tags:
        - rocm
    allow_failure: true
