[OpenCL]
# Which memory back-end to use for unspecified CLArray allocations. This can be:
# - "usm": Unified Shared Memory (`cl_intel_unified_shared_memory`)
# - "bda": plain buffers (`cl_mem` + `cl_ext_buffer_device_address`)
# - "svm": Shared Virtual Memory (coarse-grained)
# If unspecified, the default will be used based on the platform and device capabilities.
#default_memory_backend="..."
