[OpenCL]
# which memory back-end to use for CLArray allocations. This can be:
# - "auto" (default): automatically selects the best available backend
# - "usm": Unified Shared Memory (`cl_intel_unified_shared_memory`)
# - "bda": Buffer Device Address (`cl_mem` + `cl_ext_buffer_device_address`)
# - "svm": Shared Virtual Memory (coarse-grained)
#memory_backend="auto"
