steps:
  - label: "CUDA"
    plugins:
      - JuliaCI/julia#v1:
          version: "1.10"
      - JuliaCI/julia-coverage#v1:
          codecov: true
    commands: |
      julia --project -e '
        using Pkg

        println("--- :julia: Instantiating project")
        try
          Pkg.instantiate()
        catch
          # if we fail to instantiate, assume that we need newer dependencies
          Pkg.develop(path="lib/intrinsics")
        end

        println("+++ :julia: Running tests")
        Pkg.test(; coverage=true)'
    agents:
      queue: "juliagpu"
      cuda: "*"
    if: build.message !~ /\[skip tests\]/
    env:
      OCL_ICD_FILENAMES: "libnvidia-opencl.so.1"
    timeout_in_minutes: 60
