steps:
  - label: "CUDA"
    plugins:
      - JuliaCI/julia#v1:
          version: "1.12"
      - JuliaCI/julia-coverage#v1:
          codecov: true
    commands: |
      julia --project -e '
        using Pkg

        println("--- :julia: Instantiating project")
        Pkg.develop(path="lib/intrinsics")

        println("+++ :julia: Running tests")
        Pkg.test(; coverage=true, test_args=`--platform=cuda`)'
    agents:
      queue: "juliagpu"
      cuda: "*"
    if: build.message !~ /\[skip tests\]/
    env:
      OCL_ICD_FILENAMES: "libnvidia-opencl.so.1"
    timeout_in_minutes: 60
