steps:
  - label: "Julia 1.6 - CUDA"
    plugins:
      - JuliaCI/julia#v1:
          version: "1.6"
      - JuliaCI/julia-test#v1: ~
      - JuliaCI/julia-coverage#v1:
          codecov: true
    agents:
      queue: "juliagpu"
      cuda: "*"
    if: build.message !~ /\[skip tests\]/
    command: "mkdir -p /etc/OpenCL/vendors && echo libnvidia-opencl.so.1 > /etc/OpenCL/vendors/nvidia.icd"
    timeout_in_minutes: 60
