# Atomic Functions

# The atomics are relaxed LLVM atomics generated by UnsafeAtomics, which the compiler (see
# GPUCompiler's SPIR-V target) legalizes and selects to SPIR-V instructions for the device.
# They use the low-level UnsafeAtomics primitives so that the scope is emitted as given, even
# when the back-end's method tables lack GPUCompiler's overlays for UnsafeAtomics.

const atomic_float_types = [Float32, Float64]
const atomic_integer_types = [UInt32, Int32, UInt64, Int64]
const atomic_memory_types = [AS.Workgroup, AS.CrossWorkgroup]

# an atomic on global memory has to be atomic with respect to work-items of other
# work-groups, so it needs device scope; local memory is only visible within a work-group
atomic_scope(::LLVMPtr{<:Any,AS.Workgroup}) = Val(:workgroup)
atomic_scope(::LLVMPtr{<:Any,AS.CrossWorkgroup}) = Val(:device)

# `op(old, val)` stored at `p`, returning `old`
@inline atomic_modify!(p::LLVMPtr{T}, op, val::T) where {T} =
    first(UnsafeAtomics.Internal.llvm_modify!(p, op, val, Val(:monotonic), atomic_scope(p),
                                              Val(false), Val(sizeof(T)), Val(())))

# `(; old, success)` of a strong compare-and-swap
@inline atomic_cas!(p::LLVMPtr{T}, cmp::T, val::T) where {T} =
    UnsafeAtomics.Internal.llvm_cmpxchg!(p, cmp, val, Val(:monotonic), Val(:monotonic),
                                         atomic_scope(p), Val(false), Val(false),
                                         Val(sizeof(T)), Val(()))

@inline atomic_load(p::LLVMPtr{T}) where {T} =
    UnsafeAtomics.Internal.llvm_load(p, Val(:monotonic), atomic_scope(p), Val(false),
                                     Val(sizeof(T)), Val(()))


for gentype in [atomic_integer_types; atomic_float_types], as in atomic_memory_types
@eval begin

@device_function atomic_add!(p::LLVMPtr{$gentype,$as}, val::$gentype) =
    atomic_modify!(p, +, val)

@device_function atomic_sub!(p::LLVMPtr{$gentype,$as}, val::$gentype) =
    atomic_modify!(p, -, val)

# like `Base.min`/`Base.max` for floating-point numbers: NaNs propagate, and -0.0 < 0.0
@device_function atomic_min!(p::LLVMPtr{$gentype,$as}, val::$gentype) =
    atomic_modify!(p, min, val)

@device_function atomic_max!(p::LLVMPtr{$gentype,$as}, val::$gentype) =
    atomic_modify!(p, max, val)

@device_function atomic_xchg!(p::LLVMPtr{$gentype,$as}, val::$gentype) =
    atomic_modify!(p, UnsafeAtomics.right, val)

@device_function atomic_cmpxchg!(p::LLVMPtr{$gentype,$as}, cmp::$gentype, val::$gentype) =
    atomic_cas!(p, cmp, val).old

end
end

for gentype in atomic_integer_types, as in atomic_memory_types
@eval begin

@device_function atomic_inc!(p::LLVMPtr{$gentype,$as}) =
    atomic_modify!(p, +, one($gentype))

@device_function atomic_dec!(p::LLVMPtr{$gentype,$as}) =
    atomic_modify!(p, -, one($gentype))

@device_function atomic_and!(p::LLVMPtr{$gentype,$as}, val::$gentype) =
    atomic_modify!(p, &, val)

@device_function atomic_or!(p::LLVMPtr{$gentype,$as}, val::$gentype) =
    atomic_modify!(p, |, val)

@device_function atomic_xor!(p::LLVMPtr{$gentype,$as}, val::$gentype) =
    atomic_modify!(p, xor, val)

end
end

# Back-ends used to override the floating-point atomics to pick between these versions
# depending on the device's capabilities. That is now up to the compiler, so both are the
# same, and they must not call the public functions above, which those back-ends override.
for gentype in atomic_float_types, as in atomic_memory_types,
    (op, impl) in [:add => +, :sub => -, :min => min, :max => max], kind in (:native, :fallback)
    fn = Symbol("atomic_$(op)_$(kind)!")
    @eval @device_function $fn(p::LLVMPtr{$gentype,$as}, val::$gentype) =
        atomic_modify!(p, $impl, val)
end



# documentation

"""
Read the 32-bit value (referred to as `old`) stored at location pointed by `p`.
Compute `old + val` and store result at location pointed by `p`. The function
returns `old`.
"""
atomic_add!

"""
Read the 32-bit value (referred to as `old`) stored at location pointed by `p`.
Compute `old - val` and store result at location pointed by `p`. The function
returns `old`.
"""
atomic_sub!

"""
Swaps the old value stored at location `p` with new value given by `val`.
Returns old value.
"""
atomic_xchg!

"""
Read the 32-bit value (referred to as `old`) stored at location pointed by `p`.
Compute (`old` + 1) and store result at location pointed by `p`. The function
returns `old`.
"""
atomic_inc!

"""
Read the 32-bit value (referred to as `old`) stored at location pointed by `p`.
Compute (`old` - 1) and store result at location pointed by `p`. The function
returns `old`.
"""
atomic_dec!

"""
Read the 32-bit value (referred to as `old`) stored at location pointed by `p`.
Compute `(old == cmp) ? val : old` and store result at location pointed by `p`.
The function returns `old`.
"""
atomic_cmpxchg!

"""
Read the 32-bit value (referred to as `old`) stored at location pointed by `p`.
Compute `min(old, val)` and store minimum value at location pointed by `p`. The
function returns `old`.
"""
atomic_min!

"""
Read the 32-bit value (referred to as `old`) stored at location pointed by `p`.
Compute `max(old, val)` and store maximum value at location pointed by `p`. The
function returns `old`.
"""
atomic_max

"""
Read the 32-bit value (referred to as `old`) stored at location pointed by `p`.
Compute `old & val` and store result at location pointed by `p`. The function
returns `old`.
"""
atomic_and!

"""
Read the 32-bit value (referred to as `old`) stored at location pointed by `p`.
Compute `old | val` and store result at location pointed by `p`. The function
returns `old`.
"""
atomic_or!

"""
Read the 32-bit value (referred to as `old`) stored at location pointed by `p`.
Compute `old ^ val` and store result at location pointed by `p`. The function
returns `old`.
"""
atomic_xor!



#
# High-level interface
#

# prototype of a high-level interface for performing atomic operations on arrays
#
# this design could be generalized by having atomic {field,array}{set,ref} accessors, as
# well as acquire/release operations to implement the fallback functionality where any
# operation can be applied atomically.

const inplace_ops = Dict(
    :(+=) => :(+),
    :(-=) => :(-),
    :(*=) => :(*),
    :(/=) => :(/),
    :(÷=) => :(÷),
    :(&=) => :(&),
    :(|=) => :(|),
    :(⊻=) => :(⊻),
)

struct AtomicError <: Exception
    msg::AbstractString
end

Base.showerror(io::IO, err::AtomicError) =
    print(io, "AtomicError: ", err.msg)

"""
    @atomic a[I] = op(a[I], val)
    @atomic a[I] ...= val

Atomically perform a sequence of operations that loads an array element `a[I]`, performs the
operation `op` on that value and a second value `val`, and writes the result back to the
array. This sequence can be written out as a regular assignment, in which case the same
array element should be used in the left and right hand side of the assignment, or as an
in-place application of a known operator. In both cases, the array reference should be pure
and not induce any side-effects.

!!! warn
    This interface is experimental, and might change without warning.  Use the lower-level
    `atomic_...!` functions for a stable API.
"""
macro atomic(ex)
    # decode assignment and call
    if ex.head == :(=)
        ref = ex.args[1]
        rhs = ex.args[2]
        Meta.isexpr(rhs, :call) || throw(AtomicError("right-hand side of an @atomic assignment should be a call"))
        op = rhs.args[1]
        if rhs.args[2] != ref
            throw(AtomicError("right-hand side of a non-inplace @atomic assignment should reference the left-hand side"))
        end
        val = rhs.args[3]
    elseif haskey(inplace_ops, ex.head)
        op = inplace_ops[ex.head]
        ref = ex.args[1]
        val = ex.args[2]
    else
        throw(AtomicError("unknown @atomic expression"))
    end

    # decode array expression
    Meta.isexpr(ref, :ref) || throw(AtomicError("@atomic should be applied to an array reference expression"))
    array = ref.args[1]
    indices = Expr(:tuple, ref.args[2:end]...)

    esc(quote
        $atomic_arrayset($array, $indices, $op, $val)
    end)
end

# FIXME: make this respect the indexing style
@inline atomic_arrayset(A::AbstractArray{T}, Is::Tuple, op::Function, val) where {T} =
    atomic_arrayset(A, Base._to_linear_index(A, Is...), op, convert(T, val))

# native atomics
# TODO: support inc/dec
# TODO: this depends on backend support for the corresponding SPIR-V atomic
#       operation. 64-bit integer atomics require the Int64Atomics capability.
for (op,impl) in [(+)      => atomic_add!,
                  (-)      => atomic_sub!,
                  Base.max => atomic_max!,
                  Base.min => atomic_min!]
    @eval @inline atomic_arrayset(A::AbstractArray{T}, I::Integer, ::typeof($op),
                                  val::T) where {T <: Union{atomic_integer_types...,
                                                            atomic_float_types...}} =
        $impl(pointer(A, I), val)
end
for (op,impl) in [(&)      => atomic_and!,
                  (|)      => atomic_or!,
                  (⊻)      => atomic_xor!]
    @eval @inline atomic_arrayset(A::AbstractArray{T}, I::Integer, ::typeof($op),
                                  val::T) where {T <: Union{atomic_integer_types...}} =
        $impl(pointer(A, I), val)
end

# fallback using compare-and-swap
# TODO: for 64-bit types, this depends on backend support for 64-bit cmpxchg.
function atomic_arrayset(A::AbstractArray{T}, I::Integer, op::Function, val) where {T}
    ptr = pointer(A, I)
    old = atomic_load(ptr)
    while true
        cmp = old
        new = convert(T, op(old, val))
        old = atomic_cmpxchg!(ptr, cmp, new)
        # the exchange succeeded if it found the bit pattern it compared with
        old === cmp && return new
    end
end
